### ISSUE TITLE
Workspace IRI not preserved when not logged in first

### ISSUE THREAD

**Issue by jakubklimek** [opendata-mvcr/mission-control#102]
When I access e.g.  https://mission-control.netlify.app/workspaces/instance868993698 and I am not logged in, I am taken to the login screen. When I log in, I end up on my default dashboard instead of  https://mission-control.netlify.app/workspaces/instance868993698.

When I am already logged in, https://mission-control.netlify.app/workspaces/instance868993698 takes me to my workspace.

**Comment by karelklima** [comment]
Thanks for the feedback! I will definitely improve this. We're currently migrating to a different authentication provider, I'll tackle this issue as soon as it's done - likely during the weekend.
