### ISSUE TITLE
Dialog with published vocabulary shows a PR even if the publication hasn't finished yet.

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/mission-control#162]
Scenario:
1) Publish a workspace first time (works OK)
2) Make changes (in TermIt/OG)
3) Publish a workspace - now the dialog appears with the original PR (this is correct), but it appears too early, even before the publication process finishes at the server. Thus hypotetically, if the server request fails for any reason, the user will be confused at the beginning, thinking that the PR is correct w.r.t. the version (s)he wanted to publish.

![image](https://user-images.githubusercontent.com/1140626/114534559-6c677100-9c4f-11eb-95c1-c9d7f208eafe.png)

**Comment by karelklima** [comment]
Looks like a bug indeed, will look into it.
