### ISSUE TITLE
Generating IRI of legislative vocabularies fails when two number-pairs are present

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/mission-control#177]
Choosing the following text as a vocabulary label

Vyhláška č. 197/2004 Sb. (Vyhláška k provedení zákona č. 99/2004 Sb., o rybníkářství, výkonu rybářského práva, rybářské stráži, ochraně mořských rybolovných zdrojů a o změně některých zákonů (zákon o rybářství))

results in a vocabulary IRI of 

https://slovník.gov.cz/legislativní/sbírka/197/2004-99/2004

but should be 

https://slovník.gov.cz/legislativní/sbírka/197/2004

**Comment by karelklima** [comment]
That is by design. But I can modify the code to take into account only the first number pair.
