### ISSUE TITLE
Chybí text tooltipu ikony slovníku v kontrolním panelu

### ISSUE THREAD

**Issue by jakubklimek** [opendata-mvcr/mission-control#180]
# Popis problému
![image](https://user-images.githubusercontent.com/718827/125027790-1c9a1980-e087-11eb-98ee-6e731a010130.png)

# Závažnost problému
4. příliš mojí práci neovlivňuje.

**Comment by karelklima** [comment]
Opraveno, respektive odebral jsem ikonku, kdyz jsou ted vsechny slovniky pouze R/W.
