### ISSUE TITLE
Edit buttons are not activated after adding a vocabulary to a workspace

### ISSUE THREAD

**Issue by karelklima** [opendata-mvcr/mission-control#196]
Right now the edit buttons to open TermIt and ontoGrapher are disabled if there are no vocabularies in a workspace. Once a user creates a vocabulary through MC, the buttons should be activated so that the user may navigate to the respective applications.

**Comment by psiotwo** [comment]
+1 

while testing the diagrams for Milestone 1a, I had to refresh the screen cca 1G- times :-/
