### ISSUE TITLE
Middle clicking a workspace links to a 404

### ISSUE THREAD

**Issue by bindeali** [opendata-mvcr/mission-control#212]
Info:
* When I left click on a workspace from the list, I get the workspace details. This is fine. (example URL: https://xn--slovnk-7va.gov.cz/modelujeme/workspace/instance-1764959588)
* However, when I middle click on a workspace to open it in another tab, I get a 404. (example URL: https://xn--slovnk-7va.gov.cz/workspace/instance-1764959588 - **the /modelujeme/ part is missing**).

**Comment by bindeali** [comment]
Same bug with clicking on the title:
![image](https://user-images.githubusercontent.com/56399637/147859377-8c50a6d1-d5a8-41a9-85f9-5ea2dfdffb29.png)
Instead of getting https://xn--slovnk-test-scb.mvcr.gov.cz/modelujeme/workspaces, I get https://xn--slovnk-test-scb.mvcr.gov.cz/.

**Comment by karelklima** [comment]
@bindeali Should be fixed. I had to merge the PR so that I could test it on the dev instance.
