### ISSUE TITLE
V-SGoV shall be in a workspace by default

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/mission-control#49]
Or at least there should be a special button to add V-SGoV to the workspace. This would be a nice enhancement since V-SGoV is necessary in many cases, maybe all cases.

If we need to keep the tool agnostic to the kind of semantic vocabulary (i.e. independent of SGoV) this feature means that it shall be possible to configure somewhere a list of vocabularies which will be included in each workspace / their addition will be accessible via special buttons place somewhere on a visible location in the UI.

**Comment by psiotwo** [comment]
@martinnec Currently, you are proposed a set of vocabularies upon adding a vocabulary to a workspace. So it is not V-SGoV specific, but it is easy to add V-SGoV - please check.

**Comment by psiotwo** [comment]
A proposal here:
- when creating a workspace, we can choose from the same set of types as vocabularies
- **veřejný-sektor** - V-SGoV is automatically added to the workspace in R/W
- **generický** - V-SGoV is automatically added to the workspace in R; only generic vocabularies can be added/created in the workspace
- **legislativní** - V-SGoV is automatically added to the workspace in R; only generic and legislation vocabularies can be added/created in the workspace; optionally user is offered a list of Czech legislation (částka) to pick - the respective vocabulary is loaded to the workspace (in R/W?).
- **agendový** - V-SGoV is automatically added to the workspace in R; optionally, user is offered a list of Agendas to pick from. User is allowed to create a new agenda. All the laws referenced in the agenda are imported in (R/W?) to the workspace (or created in R/W); Only a single agenda/legislation/generic vocabularies can be added to the workspace.
- **datový** - V-SGoV is automatically added to the workspace in R; 

Also when a vocabulary is added to the workspace, all its (transitively) imported vocabularies are added in R to the workspace as well - configurable by a checkbox.

**Comment by psiotwo** [comment]
Implemented, closing.
