### ISSUE TITLE
Why different vocabularies for z-sgov?

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/mission-control#53]
Termit uses http://onto.fel.cvut.cz/ontologies/ufo/ IRIs

Ontographer uses https://slovník.gov.cz/základní/pojem IRIs

Why?

![image](https://user-images.githubusercontent.com/4235208/90257017-e1777200-de46-11ea-83a1-b10e5da0f07f.png)

Sorry, this issue is not related to the mission-control itself but it is above the individual tools so I specify it here.

**Comment by psiotwo** [comment]
Should be fixed already as per https://github.com/opendata-mvcr/termit/issues/6. Still old data will be there.
