### ISSUE TITLE
"Otevři v" - zvážit změnu pojmenování akcí

### ISSUE THREAD

**Issue by jakubklimek** [opendata-mvcr/mission-control#63]
Z pohledu "nováčka" mne až tak nezajímá, že existují nástroje Termit a Ontographer - musel bych to vědět dopředu a vědět, v kterém můžu co dělat, atd.

Přišlo by mi lepší zde mít spíše pojmenování toho, co s workspacem můžu dělat, což je zřejmě "Editovat" a co? no "Pojmy" a "Vztahy".

**Comment by psiotwo** [comment]
Zavírám, je to zcela vyřešeno dle požadavku.
