### ISSUE TITLE
Switch for R/O - R/W mode for a vocabulary in a workspace

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/mission-control#89]
When a vocabulary is imported to the workspace, it is imported either as read-only, or read-write. Changing from read-only to read-write is too complicated (remove a vocabulary and reimport it, selecting again the R/O or R/W mode).

The goal of the task is to create a R/W / R/O switch for a vocabulary in a workspace.

**Comment by psiotwo** [comment]
Won't solve until we decide on workspace architecture changes, as per last section in https://docs.google.com/document/d/1nEiNCdyFkxlxcvujfqMKaiXQwBWKP9cqubPGYF1cJo4/edit

**Comment by psiotwo** [comment]
FYI @marievitova

**Comment by karelklima** [comment]
@psiotwo I am not sure if this is still valid. Even if it is it seems that the API does not support the operation. I could remove the vocabulary and create it again, but it would have a different ID, I don't think we want to do that.

**Comment by psiotwo** [comment]
Does it make sense to create a R/W vocabulary out of a favourite vocabulary? Probably not.
