### ISSUE TITLE
favicon dark in dark themes

### ISSUE THREAD

**Issue by jakubklimek** [opendata-mvcr/mission-control#92]
I use dark theme in Windows and Chrome. Mission control favicon has a transparent background, making the favicon invisible.
![image](https://user-images.githubusercontent.com/718827/100756182-43a3b500-33ed-11eb-8f8e-6809196112e2.png)

**Comment by karelklima** [comment]
The transparency also make the icon look good in every other situation, but I'll think of something to improve this :-)
